### ISSUE TITLE
How to return early / short circuit the async/task?

### ISSUE THREAD

**Issue by sep2** [kekyo/FSharp.Control.FusionTasks#11]
Hi, thanks for the great library!
I encountered the issue when I want to return early with `return ()`, given `user` is actually `null`, but the code actually continue to execute causing `signInManager.PasswordSignInAsync` to throw null argument exception, how can I avoid this?

```fsharp
    [<HttpPost("sign-in")>]
    member _.SignIn(dto: SignInPortalParams) =
        let username = dto.username
        let password = dto.password

        async {
            let! user = userManager.FindByNameAsync(username)

            if isNull user
            then
                logger.LogError $"Cannot find username {username}"
                return ()

            let! result = signInManager.PasswordSignInAsync(user, password, false, false)

            if result.Succeeded
            then
                logger.LogInformation $"Sign in {user} successfully"
            else
                logger.LogError $"Sign in failed"
        }
```

**Comment by kekyo** [comment]
@sep2 Thank you report this issue, I feel it's a bug in FusionTask's monadic declaration. I'll fix it.

**Comment by sep2** [comment]
I restructured my code a bit with a more functional approach (with the help of [this library)](https://github.com/demystifyfp/FsToolkit.ErrorHandling) to bypass this issue:

```fsharp
type PortalUserController(userManager: UserManager<PortalUser>,
                          signInManager: SignInManager<PortalUser>) =
    inherit ControllerBase()

    // FSharp.Control.FusionTasks
    let findUserByName username =
        async {
            match! userManager.FindByNameAsync(username) with
            | null -> return Error("NotFound")
            | user -> return Ok(user)
        }

    // FSharp.Control.FusionTasks
    let signIn (user: PortalUser) password =
        async {
            match! signInManager.PasswordSignInAsync(user, password, false, false) with
            | r when r.Succeeded -> return Ok()
            | r -> return Error(r.ToString())
        }

    member __.SignIn(dto: SignInPortalParams): Async<IActionResult> =
        let username = dto.Username
        let password = dto.Password

        // FsToolkit.ErrorHandling
        asyncResult {
            let! user = findUserByName username
            do! signIn user password
            return user
        }
        |> AsyncResult.foldResult (fun r -> upcast __.Ok(r)) (fun e -> upcast __.BadRequest(e))
```

Inspired by [this blog post](https://medium.com/@justin_hewlett/wheres-my-early-return-ae270eb11125), maybe you don't have to fix anything here because the current behavior is probably the correct one?

**Comment by kekyo** [comment]
@sep2 I verified by F# Async type instead:

```fsharp
// NOT used FusionTasks.

let asy = async {
  if flag then
    return ()
  do! Async.Sleep 1000
}
```

These short code shows curious result same as Task and FusitonTasks. My god...

I'm interesting it causes for. Maybe F# compiler will construct Async expression from async workflow if-then-else by Compose function builder. But It doesn't (compiler or Async builder? I don't know) insert Delay function onto else block. So it will be evaluate at constructing the expression.

(I don't understand where's fixed it for the best...)

Thank you examine another solution, I will close this issue.
