### ISSUE TITLE
.NET Core/ F# Core migration

### ISSUE THREAD

**Issue by xperiandri** [kekyo/FSharp.Control.FusionTasks#3]
Is there any progress of migration to .NET Core/ F# Core?

**Comment by kekyo** [comment]
Sorry currently suspended for .NET Core migrations.
* FSharp.Core.dll for .NET Core version depends "Pre" versioned packages (ex: System.Reflection.Metadata.dll).
* So if include .NET Core version just now, forcibly marking "Pre" on FusionTasks package too... :(
* I'm waiting for remove "Pre" for all related dependencies of FSharp.Core.dll.
* Or I will be flashing across ones mind how to do another solutions... :)

**Comment by kekyo** [comment]
@xperiandri  Just available for separated package named "FSharp.Control.FusionTasks.FS40.netcore", this package will be requiring -Pre option for your project.

* And requiring FSharp.Core version is 1.0.0-alpha-161111 (and netstandard1.6) or higher.
* Referenced NuGet package is https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-alpha-161111 

Welcome feedback, thanks!

**Comment by kekyo** [comment]
If cause problem, please post new issue thread, thx.
