### ISSUE TITLE
Move source files to root folder?

### ISSUE THREAD

**Issue by rodrigovidal** [kekyo/FSharp.Control.FusionTasks#4]
Today it seems that the source files are in FSharp.Control.FusionTasks.FS3PCL47 folder, which is hard to find. Is there a specific reason for that? Could we move that to root or src folder?

**Comment by kekyo** [comment]
OK, I think so much :)
Source codes will moving to another folder, please wait.

**Comment by kekyo** [comment]
I'm refactored folder structures, source codes available only "FSharp.Control.FusionTasks" sub folder in tagged 1.0.13 ;)
