### ISSUE TITLE
Add task computation expression from Orleankka

### ISSUE THREAD

**Issue by xperiandri** [kekyo/FSharp.Control.FusionTasks#7]
Could you integrate [`task` computation expression](https://github.com/AntyaDev/Orleankka/blob/master/Source/FSharp.Api/Task.fs) from Orleankka.@
@antyadev created it because Orleans uses some tricks this Task scheduler so that it needs .NET Tasks and not F# asynchronous workflows.

I wonder why will I use F# asynchronous workflows having `task` computation expression?

**Comment by kekyo** [comment]
@xperiandri Thanks suggestion, can you send PR? :)
If you merge task comp. codes into common src folder and add items into "net45" platform fsproj, then I try to make finish another fsproj configuration!

**Comment by xperiandri** [comment]
OK, I will have a look.

**Comment by kekyo** [comment]
Sorry retired, see #14.
