### ISSUE TITLE
Merge project into a single FsProj 2017

### ISSUE THREAD

**Issue by xperiandri** [kekyo/FSharp.Control.FusionTasks#8]
What do you think about merging all the projects into a single multi-targeting project based on a new FsProj from VS 2017?

**Comment by kekyo** [comment]
I think it I have to merge all projects appropriate, perhaps release VS2017 with new F#.
VS2017 release day is near, so I think we can do it now :)

' But I don't know about how to migration new fsproj styles now.
' Do you know about it?

**Comment by xperiandri** [comment]
I know, but unfortunately VS2017 does not support fsproj-15 yet :(

**Comment by kekyo** [comment]
I know this problem, feel too...

**Comment by kekyo** [comment]
@xperiandri F# 4.5 was rollout, so FushionTasks raised up to 2.0.0 and switched completedly new MSBuild format :)
Sorry very later this issue, thanks Andrii!
